import enum
class DramaNodeType(enum.Int, export=False):
    DEFAULT = ...
    SITUATION = ...
    DIALOG = ...
    CLUB = ...
    FESTIVAL = ...
    INTERACTION = ...
    HOLIDAY = ...
    PLAYER_PLANNED = ...
    TUTORIAL = ...
    AUDITION = ...
    PICKER = ...
    VENUE_EVENT = ...
