import enum
class AutonomyStageLabel:
    BEFORE_TESTS = '1 - Before Tests'
    AFTER_TESTS = '2 - After Tests'
    BEFORE_POSTURE_SEARCH = '3 - Before Posture Search'
    AFTER_POSTURE_SEARCH = '4 - After Posture Search'
    AFTER_SCORING = '5 - After Scoring'

class GSIDataKeys(enum.Int, export=False):
    AFFORDANCE_KEY = ...
    PROBABILITY_KEY = ...
    OBJECTS_KEY = ...
    COMMODITIES_KEY = ...
    REQUEST_KEY = ...
    MIXER_PROVIDER_KEY = ...
    MIXER_SELECTED_KEY = ...
    MIXERS_KEY = ...
    MIXER_CACHING_INFO_KEY = ...
    ADDITIONAL_RESULT_INFO = ...
