from sims4.tuning.tunable import TunableRange
class FormationTuning:
    GOAL_HEIGHT_LIMIT = TunableRange(description='\n        Max value in meters between the height of the formation master and\n        the goals generated by a routing slave.\n        If the goals have a height different higher than this value, they\n        will be ignored even though the could be inside the valid constraint\n        around the master.\n        ', tunable_type=float, default=0.5, minimum=0)
